modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Zombie%20Horse%20Spawn"
logoFile="icon.png"

[[mods]]
modId="zombiehorsespawn"
version="5.1"
displayName="Zombie Horse Spawn"
displayURL="https://serilum.com/mod/zombie-horse-spawn"
authors="Rick South"
description='''Allows the zombie horse to spawn with a zombie riding it and other tweaks.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, kate1073, Michael W. S., Tyler Behl, XAgent   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.zombiehorsespawn]]
    modId="collective"
    mandatory=true
    versionRange="[7.84,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.zombiehorsespawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.2,1.21.3]"
    ordering="NONE"
    side="BOTH"
